### ISSUE TITLE
wrap_protos is missing

### ISSUE THREAD

**Issue by jean-philippe-martin** [google/clif#12]
The [primer](https://github.com/google/clif/blob/master/clif/python/primer.md#wrapping-protocol-buffers-protos) promises a `wrap_protos` example in `clif/examples/wrap_protos` but [it is not there](https://github.com/google/clif/tree/master/examples).

**Comment by mrovner** [comment]
True. It's coming in the next release.

**Comment by jean-philippe-martin** [comment]
Great! Roughly speaking, can you say what sort of release cadence you are targeting? Days, weeks, months?

**Comment by mrovner** [comment]
Target is 3-6 mo. The next (v0.3) is expecting this Sep.

**Comment by jean-philippe-martin** [comment]
Thank you very much for the quick response! Since I can't try for myself for a bit, would you perhaps be able to tell me whether clif can work with a proto file that starts with:

    syntax = "proto3";

The documentation only mentions proto2 so I'm nervous.

**Comment by gpshead** [comment]
Yes it'll work with proto2 or proto3 (it is being used with both internally already).

**Comment by mrovner** [comment]
"Official" proto 3 support comes in v0.4 (we're a bit short-handed). v0.3 will work with proto 3 but may lack some proto 3 - specific features. Filing specific bugs would helps us ensure we don't miss a feature. ;)

**Comment by jean-philippe-martin** [comment]
Thank you!
