### ISSUE TITLE
installing templates example fails - why do use gcc for compile c++ files

### ISSUE THREAD

**Issue by petacube** [google/clif#15]
/tmp/example/bin/pip install .
Processing /opt/clif/examples/templates
Installing collected packages: pyclif-example-templates
  Running setup.py install for pyclif-example-templates ... error
    Complete output from command /tmp/example/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nc/4fm6m_fd3t79jz6qyp6bhpjm0000gn/T/pip-9jr86d37\
-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/fol\
ders/nc/4fm6m_fd3t79jz6qyp6bhpjm0000gn/T/pip-npr_8vht-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/example/include/site/p\
ython3.5/pyclif-example-templates:
    running install
    running build
    running build_ext
    building 'templates' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.5
    creating build/temp.macosx-10.7-x86_64-3.5/python
    creating build/temp.macosx-10.7-x86_64-3.5/Users
    creating build/temp.macosx-10.7-x86_64-3.5
    creating build/temp.macosx-10.7-x86_64-3.5/opt
    creating build/temp.macosx-10.7-x86_64-3.5/opt/clif
    creating build/temp.macosx-10.7-x86_64-3.5/opt/clif/python
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/opt -I/anaconda3/includ\
e/python3.5m -c python/templates.cc -o build/temp.macosx-10.7-x86_64-3.5/python/templates.o -std=c++11
    In file included from python/templates.cc:8:
    /opt/clif/python/ptr_util.h:25:10: fatal error: 'type_traits' file not found
    #include <type_traits>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

**Comment by gpshead** [comment]
Any idea what compiler version that is?  we do require a fairly modern C++11 capable compiler.

http://en.cppreference.com/w/cpp/header/type_traits

**Comment by petacube** [comment]
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by mrovner** [comment]
See https://github.com/openMVG/openMVG/issues/316

**Comment by petacube** [comment]
yes thanks!
adding this this setting def helped -stdlib=libstdc++ in setup.py

**Comment by petacube** [comment]
how about this for wrapfunc
> creating build/lib.macosx-10.7-x86_64-3.5
>     g++ -bundle -undefined dynamic_lookup -Lanaconda3/lib -arch x86_64 build/temp.macosx-10.7-x86_64-3.5/python/wrapfunc.o buil\
> d/temp.macosx-10.7-x86_64-3.5/python/wrapfunc_init.o build/temp.macosx-10.7-x86_64-3.5opt/clif/python/runtime.o build/temp.maco\
> sx-10.7-x86_64-3.5opt/clif/python/slots.o build/temp.macosx-10.7-x86_64-3.5opt/clif/python/types.o /tmp/example/lib/python3.5/s\
> ite-packages/wrappod.cpython-35m-darwin.so -L./ -Lanaconda3/lib -lwrapfunc_cc_lib -o build/lib.macosx-10.7-x86_64-3.5/wrapfunc.\
> cpython-35m-darwin.so -stdlib=libc++
>     ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/tmp/example/lib/python3.5/site-packages/wrappod.cpytho\
> n-35m-darwin.so' for architecture x86_64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     error: command 'g++' failed with exit status 1

**Comment by mrovner** [comment]
See https://github.com/yallop/ocaml-ctypes-inverted-stubs-example/issues/4

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
