### ISSUE TITLE
PythonLibs and PythonInterp of python2.7 are used even if interpreter python3.6 is specified in INSTALL.sh

### ISSUE THREAD

**Issue by Solero93** [google/clif#18]
I've run the INSTALL.sh script with the following command to install using Python 3.6 as interpreter. I have Python 2.7, Python 3.5 and Python 3.6 installed on my Ubuntu 16.04LTS

```sh
./INSTALL.sh python3.6
```
It found correctly the interpreter Python 3.6, but the cmake of the install script finds Python 2.7 PythonLibs and PythonInterp on my PC. So the command pyclif runs with Python 2.7 instead of Python 3.6 as I would have wanted. 

I traced the problem to the file CLIFUtils.cmake in clif/cmake/modules where the CMake finds Python 2.7 paths. I fixed this by adding 3 new flags indicating where my PythonLibs and PythonInterp paths are on my system inside INSTALL.sh. 

The original cmake command at line 100 of the INSTALL.sh script:
```sh
cmake -DCMAKE_INSTALL_PREFIX="$CLIF_VIRTUALENV/clang" \
      -DCMAKE_PREFIX_PATH="$PROTOC_PREFIX_PATH" \
      -DLLVM_INSTALL_TOOLCHAIN_ONLY=true \
      -DCMAKE_BUILD_TYPE=Release \
      "${CMAKE_G_FLAGS[@]}" "$LLVM_DIR/llvm"
"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" clif-matcher
"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" install
```

After adding Python path flags (my own paths)
```sh
cmake -DCMAKE_INSTALL_PREFIX="$CLIF_VIRTUALENV/clang" \
      -DCMAKE_PREFIX_PATH="$PROTOC_PREFIX_PATH" \
      -DLLVM_INSTALL_TOOLCHAIN_ONLY=true \
      -DCMAKE_BUILD_TYPE=Release \
      -DPYTHON_INCLUDE_DIR="/usr/include/python3.6" \
      -DPYTHON_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython3.6m.so" \
      -DPYTHON_EXECUTABLE="/usr/bin/python3.6" \
      "${CMAKE_G_FLAGS[@]}" "$LLVM_DIR/llvm"
"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" clif-matcher
"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" install
```

Not for me, but for future users it would be nice if INSTALL.sh also changed PythonLibs and PythonInterp paths for the specified interpreter or if this workaround (if correct) was specified in the documentation.

**Comment by mrovner** [comment]
Thank you, Christian. A note added to the README (you might see it in a couple days - 0.3 is coming).
