### ISSUE TITLE
Bazel BUILD rule / BUILD file

### ISSUE THREAD

**Issue by samliu** [google/clif#20]
Feature request: a bazel build rule for CLIF :D

**Comment by mrovner** [comment]
Bad news: at the moment Bazel has no features to do so.
Good news: it's a work in progress (and we are participating).

**Comment by tinskip** [comment]
Would it be possible to use a bazel genrule for the time being?

**Comment by thaidn** [comment]
@mrovner Mike, would you mind sharing an ETA or something for this project? Thanks.

**Comment by mrovner** [comment]
My uninformative guess is around next year. I know people are actively working on this but it's hard.

**Comment by mhlopko** [comment]
https://github.com/bazelbuild/bazel/issues/4570 is the blocker.

**Comment by ChrisCummins** [comment]
Any update on this, or examples of ad-hoc workarounds with genrules?

**Comment by yegle** [comment]
The blocker was fixed recently. Any update on the bazel rules?

**Comment by hlopko** [comment]
Yup that is correct, AFAIK we can now implement clif rules in Starlark. We (the Bazel rules team) don't plan to proactively do that, but we will gladly help anybody who will.

**Comment by dmadisetti** [comment]
So there's a external project that implements clif for Bazel! See https://github.com/google/tink/commit/6c476e3e0d168dd4799ffdc6513c4686124f3d5c

I'm not sure how stale this repository is, but this hopefully reduces the engineering effort if this ticket was to ever be addressed.

**Comment by gpshead** [comment]
A little ironic given that I _believe_ @rwgk has re-implemented tink's CLIF use in pybind11 (is that released yet?).

**Comment by ChrisCummins** [comment]
FWIF, I have found that [pybind11_bazel](https://github.com/pybind/pybind11_bazel) works flawlessly and is a pleasure to use. It took a bit of figuring out how to use it as (at the time) the repo {is,was} largely undocumented. You can my example here:

https://github.com/ChrisCummins/phd/tree/master/learn/python/pybind

**Comment by dmadisetti** [comment]
@ChrisCummins Cheers. The fact the project looks pretty alive is also reassuring. Pretty easy to set up and port

**Comment by rwgk** [comment]
Yes, the tink pybind11 code was released, although the tink team is still working on building outside the google environment.

I see the author of the tink clif build rules is Bartosz, the same person I was working with when converting the clif bindings to pybind11. I wasn't aware of the tink clif build rules, but I'm pretty sure there were blockers, like clif itself not building. Bartosz' code predates him contacting me to ask when OSS clif will be updated.

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
