### ISSUE TITLE
Having a boost signal type private member, breaks clif even when its not exported to the python api

### ISSUE THREAD

**Issue by bzeller** [google/clif#25]
I try to wrap a API that supports signal/slot concepts with clif since it supports callback functions using std::function. I wrapped the boost::signals2 type inside a wrapper class to hide it from clif. However trying to generate the bindings for this code:

```c++
#include <boost/signals2.hpp>
#include <functional>

namespace Zypp{

template<typename Sig1, typename Sig2>
class SignalWrap
{
public:
  typedef typename boost::signals2::signal<Sig1 (Sig2)> SignalType;

  void onSignal (std::function<Sig1(Sig2)> cb) {
    m_sig.connect(cb);
  }

  SignalType &sig() {
    return m_sig;
  }

private:
  SignalType m_sig;
};

class MyClass
{
public:
  MyClass()
  {

  }
  int  executeCallback ( int value )
  {
    return m_sig.sig()(value).get();
  }

  SignalWrap<int, int> m_sig;
};
}
```
using this clif file:
```
from "pycliff/MyClass.h":
  namespace `Zypp`:
    class `SignalWrap<int, int>` as SignalIntInt:
      def onSignal (self, cb: (d: int) -> int)

    class MyClass:
      def executeCallback(self, d: int) -> int

      @getter
      def `m_sig` as getSig(self) -> SignalIntInt
```

Will always result in a error like this:

```
No suitable matches found for m_sig on line 9.
    Non-matching types.
    
 Compare:
    Clif Type: "Zypp::SignalWrap<int, int>" with 
     C++ Type: "::Zypp::SignalWrap<int, int>"

```
Removing the getter will make it compile , but of course I can not access the signal type. There is a workaround to have a connectToSignal() function per available signal but actually getting the signal type directly would be preferrable. 

The same result is visible for subclassing the signal, e.g:
```c++
class MySignal : public boost::signals2::signal<int (int)>
{
 ...
}
```

**Comment by mrovner** [comment]
Regardless of the type error exposing private members (like m_sig) is not supported by design.
Use the sig() getter.

**Comment by bzeller** [comment]
The m_sig exposed is not really private, but even when using a getter i would have the same error. I figured out that if the type is non copyable you get that error message. Is there a way to avoid copying the type when using a getter?

**Comment by bzeller** [comment]
The m_sig exposed is not really private, but even when using a getter i would have the same error. I figured out that if the type is non copyable you get that error message. Is there a way to avoid copying the type when using a getter?

**Comment by mrovner** [comment]
Not really. Having SignalType* sig(); might help but dangerous as C++ and Python objects might have different lifetime. The only reliable way to share is to use std::shared_ptr.

**Comment by bzeller** [comment]
Ok to recap:
- Non copyable types inside a object cause clif to fail with a seemingly unrelated error because it needs to have copyable types
- A getter is the preferred way of accessing properties
- If sharing types is required use std::shared_ptr because clif has support for that

So could that error message be fixed then? Since the behaviour itself seems to be pretty much what should happen but the error is misleading.

**Comment by mrovner** [comment]
Good recap. (Those are not strict rules, but help to avoid surprises and navigating close to the limit of supportability.)

Any suggestions to improve error reporting?

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
