### ISSUE TITLE
[Feature Request] Java Generator Support

### ISSUE THREAD

**Issue by Mizux** [google/clif#27]
Since CLIF is a "C++ wrapper generators for **various** languages." and a replacement of SWIG, I would like to have the Java (Java 8.0) support...

note: For google/or-tools we may use CLIF instead of SWIG but we need the Java support first !!!

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.

**Comment by Mizux** [comment]
> b/27133144 internally

FYI, this was marked **infeasible** internally few hours ago :clown_face:

**Comment by rwgk** [comment]
It was just a tiny technical formality, as part of a bug-bankruptcy pass. It's widely known for a very long time that Java CLIF and Go CLIG never took off, at all, and that there was no development activity at all for 6 or so years — But yes, everything leading to this particular bug-bankruptcy situation is very sad.

**Comment by jwhpryor** [comment]
Could I make a shameless plug for JNI Bind https://github.com/google/jni-bind?  

Full disclosure, I am the author, but CLIF was very much part of the inspiration, and its been under active development for years.  It's used in multiple production projects, and I personally use it every day.

Would be happy to discuss more if interested.
