### ISSUE TITLE
Suggestion for cooperation with https://github.com/mono/CppSharp

### ISSUE THREAD

**Issue by ddobrev** [google/clif#3]
Hello all,

My name is Dimitar Dobrev, one of the lead developers behind https://github.com/mono/CppSharp. I could not help but notice that your project, while initially targeting a different language, has the same purpose. CppSharp is Clang-based as well and despite the name, it's not bound to C# or .NET, generators for any languages can be added. I think we could cooperate on the subject so I would like to offer you a discussion.

**Comment by mrovner** [comment]
Hi Dimitar,

Thank you for contacting us. Not to drive anybody out, just to continue discussion I'd like to note that CppSharp looks like https://github.com/pybind/pybind11 (at least in spirit) despite implementation similarities with CLIF.
While CppSharp and pybind11 are great for people who wants more control in how the binding is implemented, they differ from CLIF idea, that the user only supplies an IDL interface description and has no control on the generated code.
Does it fit with your understanding? What ways of cooperation do you see? I boldly suggest you to create a C# frontend for CLIF that would work for a user who does not want to write any glue code.

**Comment by ddobrev** [comment]
Hello @mrovner ,

Thank you for your reply, and for the link to pybind, we definitely like to know about projects similar to ours in order to cooperate or at least exchange ideas.
My idea of cooperation was, I'm afraid, more like the other way around. At this point in time CppSharp has seen more development than CLIF so I thought that a Python language generator would be an excellent addition to advance it even more. If you feel like at least discussing such an option, I'll be looking forward to your reply.

**Comment by gpshead** [comment]
Thanks for the pointer to CppSharp! Our team isn't going to create a Python code generator for CppSharp ourselves. We are dedicated to CLIF (already widely used internally) and do not use C# internally.

But if CppSharp's design (I've only skimmed it) has the concept of interface matching to generate wrappers, reusing the same interface declaration language as much as possible for Python if anyone implements support for such a Generator for CppSharp end might make sense.

That works both ways. If anyone wants to implement C# support for CLIF, I'd want them to be aware of CppSharp to see if they need to or if there is anything useful to share.
