### ISSUE TITLE
Incorrectly states that pyparsing <=1.5.7 required. (CentOS 7) then fails to build

### ISSUE THREAD

**Issue by aborgia** [google/clif#31]
~]$ pip install 'pyparsing>=2.2.0'
Collecting pyparsing>=2.2.0
  Using cached https://files.pythonhosted.org/packages/42/47/e6d51aef3d0393f7d343592d63a73beee2a8d3d69c22b053e252c6cfacd5/pyparsing-2.2.1-py2.py3-none-any.whl
cliff 1.4.4 has requirement pyparsing<=1.5.7, but you'll have pyparsing 2.2.1 which is incompatible.
Installing collected packages: pyparsing
  Found existing installation: pyparsing 1.5.6
Cannot uninstall 'pyparsing'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Then after I install pyparsing 2.2.0 via the comment here: [https://github.com/google/clif/issues/23], it compiles and installs nicely.

**Comment by gpshead** [comment]
clif's setup.py says install requires `'pyparsing>=2.2.0',` so I'm not sure where that 1.5.7 is coming from.

**Comment by aborgia** [comment]
Agreed. I have no idea either. I checked the setup.py to ensure I was reading things correctly, and it does state 2.2.0.

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
