### ISSUE TITLE
Generator to automatic generate interface

### ISSUE THREAD

**Issue by supreme-core** [google/clif#32]
Hi,

For a larger c++ project with at least 50 headers, is it possible to use a generator to automate the process ?

**Comment by gpshead** [comment]
I expect that _could_ be done, but we haven't had a need ourselves. Our CLIF adoption has been one or two headers at a time as people find specific APIs they need access to from Python or convert an old messy SWIG wrapper into a CLIF + Python library interface.

A downside to an automated interface generator is that they tend to wrap _everything_ without an understanding of what is needed and can wrap them in non-Pythonic non-idiomatic ways.  SWIG certainly had that problem in our internal codebase.

I wouldn't reject a contribution if someone wrote such a thing, but I don't see us doing it ourselves.
