### ISSUE TITLE
Problem installing Pykaldi Compatible for of clif on Ubuntu 18.04 

### ISSUE THREAD

**Issue by ppsingh98** [google/clif#33]
I am trying to install Pykaldi compatible fork of clif in Ubuntu 18.04. Error log is enclosed. Please help to resolve the issue:

Destination /home/pp/nfr/pykaldi-master/tools/clif already exists.
/home/pp/.local/bin/ninja
Using ninja for the clif backend build.
/home/pp/nfr/pykaldi-master/tools/clif/../clif_backend/build_matcher
Start Compiling
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Could NOT find Z3 (missing: Z3_LIBRARIES Z3_INCLUDE_DIR) (Required is at least version "4.5")
-- Clang version: 5.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pp/nfr/pykaldi-master/tools/clif_backend/build_matcher
[11/12] Building CXX object tools/clif...n_utils_proto_util.dir/proto_util.cc.o
In file included from /usr/include/python2.7/Python.h:83:0,
                 from tools/clif/python/utils/proto_util.cc:7:
tools/clif/python/utils/proto_util.cc: In function ‘bool clif_python_utils_proto__util_clifwrap::Ready()’:
/usr/include/python2.7/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
tools/clif/python/utils/proto_util.cc:985:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&pyProtoTypeInfo::wrapper_Type);  // For PyModule_AddObject to steal.
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
tools/clif/python/utils/proto_util.cc:987:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&pyMethodInfo::wrapper_Type);  // For PyModule_AddObject to steal.
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
tools/clif/python/utils/proto_util.cc:989:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&pyServiceInfo::wrapper_Type);  // For PyModule_AddObject to steal.
   ^~~~~~~~~
/usr/include/python2.7/object.h:769:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
tools/clif/python/utils/proto_util.cc:991:3: note: in expansion of macro ‘Py_INCREF’
   Py_INCREF(&pyProtoFileInfo::wrapper_Type);  // For PyModule_AddObject to steal.
   ^~~~~~~~~
[12/12] Linking CXX shared library tools/clif/python/utils/proto_util.so
[160/490] Building CXX object lib/Fuzzer/CMakeFiles/LLVMFuzzerNoMainObjects.dir/FuzzerIOPosix.cpp.o
/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/lib/Fuzzer/FuzzerIOPosix.cpp: In function ‘void fuzzer::RawPrint(const char*)’:
/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/lib/Fuzzer/FuzzerIOPosix.cpp:118:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
   write(2, Str, strlen(Str));
   ~~~~~^~~~~~~~~~~~~~~~~~~~~
[260/490] Building C object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
FAILED: tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o 
/usr/bin/gcc -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_OBJC_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/c-index-test -I/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/tools/clang/tools/c-index-test -I/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/include -isystem /usr/share/doc/libxml2 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -fPIC -Werror=date-time -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG   -std=gnu89 -MD -MT tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o -MF tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o.d -o tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o   -c /home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c
/home/pp/nfr/pykaldi-master/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c:15:10: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
[261/490] Building CXX object tools/clang/tools/clang-check/CMakeFiles/clang-check.dir/ClangCheck.cpp.o
ninja: build stopped: subcommand failed.

**Comment by vrmpx** [comment]
Let me just jump into this, as to clarify why we believe this is an error on clif and not on pykaldi.
@ppsingh98 in pykaldi/pykaldi#168 mentioned that since LLVM and clang shifted from SVN to git, they downloaded the specific version corresponding to SVN trunk 307315. Then tried installing clif using our [installation scripts](https://github.com/pykaldi/pykaldi/blob/master/tools/install_clif.sh) which resulted in the reported error. However, if you were to download LLVM and clang from SVN, the script does not generate any error.

**Comment by gpshead** [comment]
LLVM recently moved from svn to git.  The script needs to be updated to grab an appropriate version using git instead (on our todo list - but we haven't focused on keeping this easily usable externally).

**Comment by ArashHosseini** [comment]
same here, [issue](https://github.com/pykaldi/pykaldi/issues/184)

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
