### ISSUE TITLE
Do we still not take contributions at this point? It is way past 2H 2017.

### ISSUE THREAD

**Issue by rainwoodman** [google/clif#40]
https://github.com/google/clif/blob/83ca1bc29cfc0d56eb828b02871c1ef303ef9251/CONTRIBUTING.txt#L15

**Comment by gpshead** [comment]
This is becoming less true.  Our CLA bot is active on PRs (yay).  But I'm not sure if we're ready to _merge_ PRs externally directly vs still needing to go through our internal source of truth codebase; a PR is still a good communication mechanism for a proposed change regardless.

**Comment by rwgk** [comment]
No, not ready, sorry. I think the biggest obstacle is that we would need reversible copybara transformations. For code it may not be too bad, but I'm really worried about .md files.

**Comment by rwgk** [comment]
Closing this for now. We're currently not staffed to improve OSS support, but I will look at incoming PRs and take care of them manually, if feasible.

**Comment by rainwoodman** [comment]
Sounds good. Thanks!
