### ISSUE TITLE
Error during installtion

### ISSUE THREAD

**Issue by narendrachaudhary51** [google/clif#41]
Hi,

I get the following error during installation using ./INSTALL.sh. I am using the clang and llvm 11.0.0 on Centos 7

Scanning dependencies of target clif-matcher
[100%] Building CXX object clif/backend/CMakeFiles/clif-matcher.dir/matcher_main.cc.o
[100%] Linking CXX executable clif-matcher
CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE[_ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE]+0x18): undefined reference to `typeinfo for llvm::cl::Option'
CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyIbEE[_ZTIN4llvm2cl15OptionValueCopyIbEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
libclifMatcher.a(ast.cc.o):(.data.rel.ro._ZTIN4clif18TranslationUnitAST24ConversionFunctionFinderE[_ZTIN4clif18TranslationUnitAST24ConversionFunctionFinderE]+0x10): undefined reference to `typeinfo for clang::ast_matchers::MatchFinder::MatchCallback'

**Comment by rwgk** [comment]
Sorry for the delay in responding.
Did you solve the problem in the meantime?

**Comment by narendrachaudhary51** [comment]
No. I am not able to solve this problem yet.

**Comment by rwgk** [comment]
@akekawit, could you please help?

**Comment by akekawit** [comment]
That's odd. I just tried building CLIF on centos 7 with LLVM/clang 11.0.0, and it was able to link clif-matcher just fine. How did you build/install LLVM/clang?

I can try putting together a dockerfile/github workflow that build/test on centos 7 as an example later too.

**Comment by narendrachaudhary51** [comment]
I do not have sudo access so I needed to install everything in my local directory. Installation of googletest also caused some issues so I had to manually move some files. 
Docker/github workflow will be really helpful. If you can post series of commands you used that can also be helpful.

**Comment by rwgk** [comment]
Closing this very old issue. If you still have a problem, please open a new issue and tag me there for a faster response.
