### ISSUE TITLE
Error during on Pip installtion

### ISSUE THREAD

**Issue by MasterLivens** [google/clif#42]
After make successful. I got the file 'ast_pb2.py', but still some files missing below here.

cp "$BUILD_DIR/clif/python/utils/proto_util.cc" clif/python/utils/
cp "$BUILD_DIR/clif/python/utils/proto_util_clif.h" clif/python/utils/
cp "$BUILD_DIR/clif/python/utils/proto_util.init.cc" clif/python/utils/

![Snipaste_2021-01-14_14-17-52](https://user-images.githubusercontent.com/15192583/104552210-527bb980-5673-11eb-9beb-f7f1d8d0faa1.png)

**Comment by rwgk** [comment]
Sorry for the long delay. This isn't enough information for me to know what exactly went wrong. If this is still relevant to you, could, please reopen this issue and tag me for a faster response. Please include all steps to reproduce the failure.

**Comment by benjaminfang** [comment]
Hi,
If you just run:
`make clif-matcher` or `ninja clif-matcher`, it is not enough, and you still need to run: `make clif_python_utils_proto_util` or `ninja clif_python_utils_proto_util`. after make clif_python_utils_proto_util, the file which missed will be generated.
and you can carry on remain steps.
Good luck.
