### ISSUE TITLE
Clif LLVM Installation Error

### ISSUE THREAD

**Issue by aliceseaborn** [google/clif#43]
I am trying to install Clif v0.4 from source in CentOS 7 as a prerequisite for DeepVariant. I am using CMake 1.15.2 and GCC 8.2.0. I have a Python environment (Python 3.6.12) named deepvariant in Anaconda3 that is running with virtualenv 20.4.2 and pyparsing 2.2.0 installed. The latest Absiel is installed and the path is set using the absl_DIR environment variable. Protobuf 3.15.1 and Glog 0.4.0 are installed and the paths are set using:
```BASH
export PKG_CONFIG_PATH="/opt/apps/glog/0.4.0:/opt/apps/protobuf/3.15.1/cpp"
pkg-config --cflags protobuf libglog
```

Using CMake, I install Clif using the following command, specifying where the python prerequisites can be installed:
```BASH
cmake .. \
  -DPYTHON_INCLUDE_DIR="/opt/apps/Anaconda3/2020.07/envs/deepvariant/include/" \
  -DPYTHON_LIBRARY="/opt/apps/Anaconda3/2020.07/envs/deepvariant/lib/" \
  -DPYTHON_EXECUTABLE="/opt/apps/Anaconda3/2020.07/envs/deepvariant/bin/python3"
```

Unfortunately, I run into the following error:
```BASH
(deepvariant) [root@machine]# cmake ..   -DPYTHON_INCLUDE_DIR= ...
CMake Error at clif/cmake/modules/CLIFUtils.cmake:37 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/llvm/LLVMConfig.cmake, version: 11.1.0

Call Stack (most recent call first):
  clif/CMakeLists.txt:22 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/apps/clif/0.4/build/CMakeFiles/CMakeOutput.log".
See also "/opt/apps/clif/0.4/build/CMakeFiles/CMakeError.log".
```

Originally, the latest main branch of LLVM was installed to /opt/apps/llvm/latest/  but I received an error stating that version 13.x.x git was installed there and was not compatible. Over night, I built the 11.1.0 release version of LLVM and let it install to /usr/local/... so that Clif could easily find it. I repeatably hit this compatibility error. Clif did not specify any minor release or patch incompatibilities for LLVM 11+ so I assumed that version 11+ should work just fine. How do I complete this installation? Please advise.

**Comment by rwgk** [comment]
Sorry the clif/issues fell completely off my radar.
We had the same problem that was fixed with this commit: https://github.com/google/clif/commit/d834b0fd8383b821ba506152bc8ee40a54211985
Please reopen this issue and tag me for a faster response if this is still relevant.

**Comment by benjaminfang** [comment]
Hi,
by edit clif-0.4/clif/cmake/modules/CLIFUtils.cmake maybe help.
to change the line: find_package(LLVM 11 REQUIRED)  to find_package(LLVM 11.1.0 REQUIRED)
