### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by yanyang1989** [google/clif#44]
I have run the Dockerfile for prereqs and changed the basic image to ubuntu 20.04 and didn't pass the whole process. I was wondering it is supported on ubuntu 20.04 or any other suggestion to install clif in a basic image of ubuntu 20.04. Thanks

**Comment by rwgk** [comment]
I think this was fixed by this commit: https://github.com/google/clif/commit/b865c88beff70b31068889926d1184d5ddc0b9eb

Sorry for the long delay responding.
