### ISSUE TITLE
Replace http://go link in README.md

### ISSUE THREAD

**Issue by xeno14** [google/clif#45]
The below link in [clif/clif/python/README.md](https://github.com/google/clif/blob/main/clif/python/README.md) is broken. Should replace http://go with GitHub pages?

[The `Status` and `StatusOr<T>` classes in Python wrappers](http://go/absl-status-python-wrappers)

https://github.com/google/clif/blame/main/clif/python/README.md#L38

**Comment by rwgk** [comment]
Thanks for pointing this out! But sorry, currently the target page doesn't exist on GitHub, therefore I simply removed the broken link for now: https://github.com/google/clif/commit/bcdb44a153f377c4b61f9a9723994f47049e3460

`Status` and `StatusOr` don't actually work with the GitHub version of PyCLIF. We need to clean up the internal version first to refactor the pre-abseil organization to straightforwardly use the abseil types. That will take a while (difficult to give a timeline).
