### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [google/clif#46]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine clif/pybind11/function_lib.py and observe `unncessary`, however expect to see `unnecessary`.
- Examine clif/python/gen.py and observe `sinature`, however expect to see `signature`.
- Examine examples/inheritance/python/operation_test.py and observe `inheritence`, however expect to see `inheritance`.
- Examine clif/testing/t9.h and observe `hierarhies`, however expect to see `hierarchies`.
- Examine clif/backend/matcher.h and observe `formattting`, however expect to see `formatting`.
- Examine clif/python/pytd2proto.py and observe `exising`, however expect to see `existing`.
- Examine clif/python/pytd2proto.py and observe `errorneously`, however expect to see `erroneously`.
- Examine clif/python/gen.py and observe `elmement`, however expect to see `element`.
- Examine clif/testing/python/pickle_compatibility_unpickle_subtest_binary.py and observe `compatiblity`, however expect to see `compatibility`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/clif/pull/new/bugfix_typos

Thanks.

**Comment by rwgk** [comment]
Thanks for pointing out the spelling errors! We're not set up for PRs, but I simply manually transferred them over internally and then pushed them back out: https://github.com/google/clif/commit/bcdb44a153f377c4b61f9a9723994f47049e3460
