### ISSUE TITLE
Bazel rules

### ISSUE THREAD

**Issue by tweeter0830** [google/clif#5]
Is there any chance that this can be built and used with Bazel? It would be sweet to be able to generate c++ wrappers simply in bazel.

**Comment by mrovner** [comment]
Not yet, sorry. See https://github.com/google/clif/issues/1

**Comment by davidzchen** [comment]
Seems that the Bazel rules are available here: https://github.com/google/clif/blob/main/clif_build_rule.bzl

**Comment by rwgk** [comment]
> Seems that the Bazel rules are available here: https://github.com/google/clif/blob/main/clif_build_rule.bzl

Sorry the checked-in code is incomplete. Started, but not finished. We took a snapshot before the volunteer working on it had to move on. It's been in this state for three years or so.

**Comment by davidzchen** [comment]
Thanks for clarifying. Should we reopen this bug then?
