### ISSUE TITLE
How to handle "Function template can't be specialized with these arguments."

### ISSUE THREAD

**Issue by dogancan** [google/clif#7]
What is the standard/recommended way of handling the error "Function template can't be specialized with these arguments." ?

Consider the following header file.
```
template<typename Real>
class ArrayBase {
 public:
  void CopyFromArray(const ArrayBase<Real> &v);

  template<typename OtherReal>
  void CopyFromArray(const ArrayBase<OtherReal> &v);
};
```
This CLIF wrapping 
```
from "array.h":
  class `ArrayBase<float>` ArrayBase:

    def CopyFromArray(self, a: ArrayBase)  # This is the error

```
leads to this error
```
No suitable matches found for CopyFromArray on line 5.
    Multiple C++ symbols with same name found. Possibilities include:
    Rejected Candidate:
      ArrayBase<float>::CopyFromArray at /home/dogan/tools/pyarray/array.h:110:3
    Rejected Candidate:
      ArrayBase<float>::CopyFromArray<float> at /home/dogan/tools/pyarray/array.h:118:3
No suitable matches found for CopyFromArray on line 5.
    Function template can't be specialized with these arguments.
```

**Comment by mrovner** [comment]
Unlike C++ that has strict rules for overload resolution, CLIF by design fails if it finds several definitions ("In the face of ambiguity, refuse the temptation to guess." (c)).

We'll need some time to decide how to handle this case.

**Comment by mrovner** [comment]
We decided that CLIF will not support this case. 

Unlike pure C++ call where we can tell exactly what is the actual parameter type,
CLIF selects the exact type to call C++ with. The user can't say "use only type T", so on each selection CLIF makes we can come up with a case that will call the "wrong" C++ function in the generated code.

The recommended workaround here is to create an alias in C++ that solves the ambiguity and wrap that alias.
```
  template<typename OtherReal>
  void OtherCopyFromArray(const ArrayBase<OtherReal> &v);
```
