### ISSUE TITLE
Hello, I meet problems while I running the ./INSTALL.sh files, The problem is: No package 'protobuf' found

### ISSUE THREAD

**Issue by pioneer-pi** [google/clif#83]
The detail problem: 
```
+++ dirname ./INSTALL.sh
++ cd .
++ pwd
+ CLIFSRC_DIR=/root/clif
+ BUILD_DIR=/root/clif/build
+ declare -a CMAKE_G_FLAG
+ declare -a MAKE_PARALLELISM
+ which ninja
+ CMAKE_G_FLAGS=()
+ MAKE_OR_NINJA=make
+ MAKE_PARALLELISM=(-j 2)
+ [[ -r /proc/cpuinfo ]]
++ cat /proc/cpuinfo
++ grep -c '^processor'
+ N_CPUS=32
+ [[ 32 -gt 0 ]]
+ MAKE_PARALLELISM=(-j $N_CPUS)
+ MAKE_INSTALL_PARALLELISM=(${MAKE_PARALLELISM[@]})
+ echo 'Using make for the clif backend build.'
Using make for the clif backend build.
+ [[ '' =~ ^-?-h ]]
+ [[ -n '' ]]
++ which python3
+ PYTHON=/usr/local/bin/python3
+ echo -n 'Using Python interpreter: /usr/local/bin/python3'
Using Python interpreter: /usr/local/bin/python3+ [[ '' -eq 1 ]]
+ mkdir -p /root/clif/build
+ cd /root/clif/build
+ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
-- Checking for module 'protobuf'
--   No package 'protobuf' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  clif/cmake/modules/CLIFUtils.cmake:31 (pkg_check_modules)
  clif/CMakeLists.txt:22 (include)
```
Thanking for you help!

**Comment by rwgk** [comment]
The INSTALL.sh script is regularly exercised in this workflow:

https://github.com/google/clif/blob/main/.github/workflows/examples.yml

Without being able to look closely:

I think most likely you're missing a step preparing your platform. Could you please try to follow the steps in this Dockerfile as closely as possible?

https://github.com/google/clif/blob/main/Dockerfile

Small warning: While PyCLIF is the predominant Python/C++ bindings tool used internally at Google, I'm aware of only one external project depending on it. Generally I recommend using https://github.com/pybind/pybind11 externally, which has a vastly bigger user base. The advantages of using PyCLIF over pybind11 only play out when used at scale.

**Comment by pioneer-pi** [comment]
Thank you for you advice, I will try it.
